### ISSUE TITLE
Move: Dark Void (purple)

### ISSUE THREAD

**Issue by shutterbug2000** [KaeruTeam/duel-issue-tracker#15]
Move: Dark Void (purple)

**Comment by shutterbug2000** [comment]
Note: Not sure whether the move is a never-ending turn or unexpected error, so adding both tags.

**Comment by shutterbug2000** [comment]
Appears to be resolved, but can reopen if needed.

**Comment by Haileselasie** [comment]
This still crashes the game. Due to field spins
