### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Haileselasie** [KaeruTeam/duel-issue-tracker#20]
I don't think confusion worked properly. Even though he protected the Pokemon that was confused it should have still shifted one over. 
![Screen_Recording_20201014-173207_Pokmon Duel_1](https://user-images.githubusercontent.com/72710530/96047952-e3a87d80-0e43-11eb-8581-a744d521f010.gif)

**Comment by shutterbug2000** [comment]
Any idea which move inflicted the confusion?

**Comment by Haileselasie** [comment]
Yes it was a Z move
![Screen_Recording_20201014-173207_Pokmon Duel_2](https://user-images.githubusercontent.com/72710530/96090293-fcda1a00-0e95-11eb-8655-99008e22fe53.gif)
