### ISSUE TITLE
More cards

### ISSUE THREAD

**Issue by Haileselasie** [KaeruTeam/duel-issue-tracker#21]
Is it possible to add double chance and Max revive? This can help out testing a lot also. 
![received_747550669424047](https://user-images.githubusercontent.com/72710530/96049043-7990d800-0e45-11eb-9055-4e6de40bbb91.jpeg)
![received_380581146307357](https://user-images.githubusercontent.com/72710530/96049044-7a296e80-0e45-11eb-9368-8c8109f9a4bf.jpeg)

**Comment by shutterbug2000** [comment]
I'll add them in a little bit
