### ISSUE TITLE
Treecko wall climb does not work

### ISSUE THREAD

**Issue by X-ANAX** [KaeruTeam/duel-issue-tracker#24]
Ability wall climb does not work past non ghost figures as described

**Comment by MonochromeKirby** [comment]
Was it on the bench when you tried to use the ability?

**Comment by X-ANAX** [comment]
No it was on fields and would not pass through charmander

**Comment by MonochromeKirby** [comment]
That's because Treecko's ability only works while it's on the bench. So, that's working as intended.

**Comment by X-ANAX** [comment]
Issue resolved
