### ISSUE TITLE
Popplio missing abilitiy

### ISSUE THREAD

**Issue by D-Rocket** [KaeruTeam/duel-issue-tracker#5]
Popplio is missing its ability

**Comment by shutterbug2000** [comment]
Seemingly a mix-up, so I'm going to close. Feel free to clarify and reopen if I'm missing something!

**Comment by D-Rocket** [comment]
I think you may be rightOn 14 Oct 2020 11:08 am, shutterbug2000 <notifications@github.com> wrote:
Seemingly a mix-up, so I'm going to close. Feel free to clarify and reopen if I'm missing something!
