### ISSUE TITLE
Munchlax

### ISSUE THREAD

**Issue by Haileselasie** [KaeruTeam/duel-issue-tracker#59]
Eats Anything, move freezes the game. Even if there are plates on the field it's still stalls the game.

Switches one of the opponent's plates from unused to used. When this Pokémon (or a Pokémon that evolved from this Pokémon) leaves the field, return as many plates as were switched to be used with this Attack since this Pokémon entered the field back to unused

![Screenshot_20210204-184918_Pokmon Duel](https://user-images.githubusercontent.com/72710530/106969876-bdbc2700-6719-11eb-87fd-9cf087d23fc5.jpg)

**Comment by shutterbug2000** [comment]
Figure blacklisted
