### ISSUE TITLE
Duel ID 7100

### ISSUE THREAD

**Issue by Haileselasie** [KaeruTeam/duel-issue-tracker#75]
It crashed after the second attack. 

![Screenshot_20210325-020723_Pokmon Duel.jpg](https://user-images.githubusercontent.com/72710530/112426818-f71f1500-8d0e-11eb-80ad-5ddaeeb67004.jpg)

**Comment by shutterbug2000** [comment]
The underlying cause of this should be resolved. Thanks for the report!
